version: "3.8"

services:
  screenshot-service:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./cache:/app/cache
      - ./src:/app/src
    command: npm run dev
    environment:
      - PORT=3000
    restart: unless-stopped
