version: "3.8"

services:
  screenshot-service:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - screenshot-cache:/app/cache
    environment:
      - PORT=3000
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

volumes:
  screenshot-cache:
    name: screenshot-cache
